name: Go

on: [push]

jobs:
  build:


    run-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [1.14x,1.15.x, 1.16.x]
      
    steps:
      - uses: actions/checkout@v3
      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}

      - name: Display Go version
        run: go version



         